name: System Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.8]

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 12345:3306
        env:
          MYSQL_ROOT_PASSWORD: 'RootPassphrase' # password for root account
          MYSQL_DATABASE: 'exoskeleton' # database to be created on image startup
          MYSQL_USER: 'exoskeleton' # User with all right for exoskeleton database
          MYSQL_PASSWORD: 'exoskeleton' # Password for the exoskelton user


    steps:
      - uses: actions/checkout@v2

      - name: Make a directory to store downloads
        run: mkdir ./fileDownloads

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: APT Update
        run: sudo apt update

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chromium
        run: sudo apt install chromium-browser

      # The next step need to wait until the MariaDB container is ready.
      # This pings it until it gets an answer:
      - name: Wait for MariaDB to initialize
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"12345" --silent; do
            sleep 1
          done


      - name: Fill exoskeleton database
        env:
          PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          mysql --host='127.0.0.1' -P"$PORT" --user='root' --password='RootPassphrase' exoskeleton < 'Database-Scripts/Generate-Database-Schema-MariaDB.sql'

      - name: Run Systemtest
        run: python3 system-test.py

      - name: List downloaded files
        run: ls -l ./fileDownloads
